routes/web.php
<?php

Route::prefix('canticos')->middleware(['web', 'addon:songbook'])->name('songbook.')->namespace('Sautor\Songbook\Controllers')->group(function () {
    Route::middleware(['auth'])->group(function () {
        Route::resource('etiquetas', 'TagsController')->parameter('etiquetas', 'tag');
        Route::resource('canticos', 'SongsController')->parameter('canticos', 'song');
        Route::resource('folhas', 'SheetsController')->parameter('folhas', 'sheet');
    });

    Route::get('/', 'PublicController@index')->name('index');
    Route::get('{sheet}', 'PublicController@show')->name('public.show');
});

resources/views/home-content.blade.php
@php($sheets = \Sautor\Songbook\Models\Sheet::nextWeek()->public()->get())
@unless($sheets->isEmpty())
  @php($allDates = $sheets->pluck('dates')->flatten())

  <div class="s-sb-container s-sb-mx-auto s-sb-px-8 s-sb-pt-16">
    <div class="s-sb-rounded-lg s-sb-drop-shadow-lg s-sb-bg-gray-800 s-sb-text-white s-sb-px-6 s-sb-py-4 s-sb-flex s-sb-flex-col md:s-sb-flex-row md:s-sb-items-center s-sb-gap-4">
      <div class="s-sb-rounded-full s-sb-w-10 s-sb-h-10 s-sb-bg-gray-600 s-sb-flex s-sb-items-center s-sb-justify-center">
        <span class="fas fa-music s-sb-text-gray-50 s-sb-scale-125"></span>
      </div>

      <div class="s-sb-flex-1">
          <h2 class="s-sb-font-headline s-sb-text-white s-sb-text-lg">Cânticos</h2>

          <p>
            Estão disponíveis os <strong>cânticos</strong> para
            {{ $allDates->map(function ($date) { return lcfirst($date->calendar()); })->join(', ', ' e ') }}.
          </p>
        </div>

      <a href="{{ route('songbook.index') }}" class="s-sb-inline-block s-sb-rounded s-sb-px-6 s-sb-py-2 s-sb-font-accent s-sb-border-2 s-sb-border-white s-sb-self-end md:s-sb-self-center hover:s-sb-text-gray-800 hover:s-sb-bg-white s-sb-transition-colors s-sb-duration-300">
        Ver
        <span class="far fa-arrow-right ml-1"></span>
      </a>

    </div>
  </div>
@endunless


@push('styles')
  <link rel="stylesheet" href="{{ asset('addons/songbook/style.css') }}">
@endpush

resources/views/layouts/main.blade.php
@extends('layouts.app')
@section('content')
  @include('songbook::layouts.partials.header')
  @yield('sb.content')
@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('addons/songbook/style.css') }}">
@endpush

resources/views/layouts/partials/header.blade.php
<x-addon-header name="Cânticos" icon="fas fa-music">
  @can('gerir cânticos')
    <x-slot:nav>
      <a href="{{ route('songbook.canticos.index') }}">
        <span class="fas fa-music-alt"></span>
        Cânticos
      </a>
      <a href="{{ route('songbook.etiquetas.index') }}">
        <span class="fas fa-tag"></span>
        Etiquetas
      </a>
      <a href="{{ route('songbook.folhas.index') }}">
        <span class="fas fa-list-music"></span>
        Folhas
      </a>
    </x-slot:nav>
  @endcan
</x-addon-header>

resources/views/sheets/create.blade.php
@extends('songbook::layouts.main')

@section('sb.content')
  <div class="sautor-addon__full-container">
    <header class="sautor-addon__header">
      <h1 class="sautor-addon__header__title">
        Criar folha de cânticos
      </h1>
    </header>

      @php($scope = 'new-sheet')
      <form action="{{ route('songbook.folhas.store') }}" method="POST" data-vv-scope="{{ $scope }}">
        @csrf

        @include('songbook::sheets.form')

        <div class="sautor-addon__actions">
          <button type="submit" class="button button--primary">Criar</button>
        </div>
      </form>
  </div>
@endsection

resources/views/sheets/edit.blade.php
@extends('songbook::layouts.main')

@section('sb.content')
  <div class="sautor-addon__full-container">
    <header class="sautor-addon__header">
      <h1 class="sautor-addon__header__title">
        Editar folha de cânticos
      </h1>
    </header>

      @php($scope = 'edit-sheet')
      <form action="{{ route('songbook.folhas.update', $sheet) }}" method="POST" data-vv-scope="{{ $scope }}">
        @method('PUT')
        @csrf

        @include('songbook::sheets.form')

        <div class="sautor-addon__actions">
          <button type="submit" class="button button--primary">Editar</button>
          @can('delete', $sheet)
            <button type="button" class="button button--danger-light" @click.prevent="openModal('deleteModal')">
              <span class="far fa-trash mr-2"></span>
              Eliminar
            </button>
          @endcan
        </div>

      </form>

    </div>

  @can('delete', $sheet)
    <modal id="deleteModal">
      <div class="modal__body modal__confirmation">
        <div class="modal__confirmation__icon">
          <span class="fas fa-exclamation"></span>
        </div>
        <div class="modal__confirmation__content">
          <h3 class="modal__confirmation__title">Eliminar cântico</h3>
          <p class="modal__confirmation__text">
            Tem a certeza que quer eliminar a folha <strong>{{ $sheet->title }}</strong>?
          </p>
        </div>
      </div>
      <form class="modal__footer" method="POST" action="{{ route('songbook.folhas.destroy', $sheet) }}">
        @csrf
        @method('DELETE')
        <button type="submit" class="button button--danger">Eliminar</button>
        <button type="button" class="button" @click.prevent="closeModal('deleteModal')">Cancelar</button>
      </form>
    </modal>
  @endcan
@endsection

resources/views/sheets/index.blade.php
@extends('songbook::layouts.main')

@section('sb.content')
  <div class="sautor-addon__container">

    <header class="sautor-addon__header">
      <h1 class="sautor-addon__header__title">
        Folhas de cânticos
      </h1>
      @can('create', \Sautor\Songbook\Models\Sheet::class)
        <div class="sautor-addon__header__actions">
          <a href="{{ route('songbook.folhas.create') }}" class="button button--responsive">
            <span class="far fa-plus"></span>
            Criar
          </a>
        </div>
      @endcan
    </header>

      @include('songbook::sheets.list-component')

    @if(method_exists($sheets, 'links'))
      <div class="mt-4">
        {{ $sheets->links() }}
      </div>
    @endif

  </div>
@endsection

resources/views/sheets/item.blade.php
<div class="sautor-list__item">
  @if($item['type'] === 'song')
    <div class="sautor-list__item__logo">
      <span class="sautor-list__item__logo__icon sautor-list__item__logo__icon--strong">
        <span class="fas fa-music-alt"></span>
      </span>
    </div>
    <a href="{{ route('songbook.canticos.show', $item['song']) }}" class="sautor-list__item__data">
      <p class="sautor-list__item__name">
        {{ $item['song']->title }}
      </p>
      @if(array_key_exists('label',$item))
        <p class="sautor-list__item__meta">
          {{ $item['label'] }}
        </p>
      @endif
    </a>
  @elseif($item['type'] === 'heading')
    <div class="sautor-list__item__logo">
      <span class="sautor-list__item__logo__icon sautor-list__item__logo__icon--strong">
        <span class="fas fa-heading"></span>
      </span>
    </div>
    <div class="sautor-list__item__data">
      <p class="sautor-list__item__name">
        {{ $item['content'] }}
      </p>
      <p class="sautor-list__item__meta">
        Nível {{ $item['level'] }}
      </p>
    </div>
  @elseif($item['type'] === 'groups')
    <div class="sautor-list__item__logo">
      <span class="sautor-list__item__logo__icon sautor-list__item__logo__icon--strong">
        <span class="fas fa-users"></span>
      </span>
    </div>
    <div class="sautor-list__item__data">
      <p class="sautor-list__item__name">
        Lista de grupos
      </p>
      <p class="sautor-list__item__meta">
        {{ $item['groups']->pluck('nome_curto')->join(', ') }}
      </p>
    </div>
  @else
    <div class="sautor-list__item__logo">
      <span class="sautor-list__item__logo__icon sautor-list__item__logo__icon--strong">
        <span class="fas fa-question"></span>
      </span>
    </div>
    <div class="sautor-list__item__data">
      <p class="sautor-list__item__name">Desconhecido</p>
    </div>
  @endif
</div>

resources/views/sheets/list-component.blade.php
@unless($sheets->isEmpty())
  <section class="sautor-list sheets-list">
    @foreach($sheets as $sheet)
      <div class="sautor-list__item">
        <div class="sautor-list__item__logo">
          @if($sheet->grupo and $sheet->grupo->logo)
            <img src="{{ $sheet->grupo->logo }}" alt="{{ $sheet->grupo->nome }}">
          @else
            <span class="sautor-list__item__logo__icon sautor-list__item__logo__icon--strong">
                <span class="fas fa-list-music"></span>
            </span>
          @endif
        </div>
        <a href="{{ route('songbook.folhas.show', $sheet) }}" class="sautor-list__item__data">
          <p class="sautor-list__item__name">
            {{ $sheet->title }}
          </p>
          <p class="sautor-list__item__meta">
            {{ $sheet->dates->map(function($date) { return $date->isoFormat('lll'); })->join(', ') }}
            @if($sheet->grupo)
            &middot; {{ $sheet->grupo->nome }}
            @endif
          </p>
        </a>

        <div class="sautor-list__item__actions">
          @unless(empty($actions) or empty($a = $actions($sheet)))
            @foreach($a as $action)
              <a title="{{ $action['label'] }}"
                 @if(!empty($action['link']))
                 href="{{ $action['link'] }}"
                 @elseif(!empty($action['modal']))
                 href="#" data-toggle="modal" data-target="#{{ $action['modal'] }}"
                      @endif
              >
                <span class="{{ $action['icon'] }}"></span>
              </a>
            @endforeach
          @endunless
          <a title="Ver" href="{{ route('songbook.folhas.show', $sheet) }}">
            <span class="far fa-angle-right"></span>
          </a>
        </div>
      </div>
    @endforeach
  </section>
@else
  <section class="sautor-list--empty tags-list--empty">
    {{ empty($empty_message) ? 'Não existem folhas de cânticos.' : $empty_message }}
  </section>
@endunless

resources/views/sheets/print.blade.php
@extends('resources::layout', ['hideFooter' => true])

@section('title')
  {{ $sheet->title }}
@endsection

@section('content')
  <div class="print__header">
    @include('resources::resources.partials.logo')
    @isset($grupo)
      @include('resources::resources.partials.group-logo')
    @endisset
  </div>

  @include('songbook::sheets.display')
@endsection

@push('styles')
  <link rel="stylesheet" href="{{ asset('addons/songbook/style.css') }}">
@endpush

resources/views/sheets/show.blade.php
@extends('songbook::layouts.main')

@section('sb.content')
  <div class="sautor-addon__container">

    <header class="sautor-addon__header">
      <h1 class="sautor-addon__header__title">
        {{ $sheet->title }}
        <small>Folha de cânticos</small>
      </h1>
        <div class="sautor-addon__header__actions">
          <dropdown>
            <template v-slot:default="{ toggle }">
              <button type="button" class="button button--responsive" @click="toggle">
                <span class="far fa-eye"></span>
                Ver
              </button>
            </template>

            <template v-slot:dropdown>
              <a href="{{ route('songbook.public.show', $sheet) }}" class="dropdown__item">
                <span class="dropdown__item__icon far fa-fw fa-eye"></span>
                Ver
              </a>
              <a href="{{ route('songbook.public.show', $sheet) }}?acordes" class="dropdown__item">
                <span class="dropdown__item__icon far fa-fw fa-guitar"></span>
                Ver acordes
              </a>

              @if($sheet->hasMedia('pdf') or $sheet->hasMedia('pdf-chords'))
                <div class="dropdown__divider dropdown__divider--with-icon"></div>

              @if($sheet->hasMedia('pdf'))
                    <a href="{{ $sheet->getFirstMediaUrl('pdf') }}" class="dropdown__item">
                      <span class="dropdown__item__icon far fa-fw fa-file-pdf"></span>
                      PDF
                    </a>
                  @endif
                  @if($sheet->hasMedia('pdf-chords'))
                    <a href="{{ $sheet->getFirstMediaUrl('pdf-chords') }}" class="dropdown__item">
                      <span class="dropdown__item__icon fa-layers fa-fw">
                         <span class="far fa-file"></span>
                         <span class="fas fa-guitar" data-fa-transform="shrink-10 down-2"></span>
                      </span>
                      PDF Acordes
                    </a>
                  @endif
              @endif
            </template>
          </dropdown>

          @can('update', $sheet)
          <a href="{{ route('songbook.folhas.edit', $sheet) }}" class="button button--responsive">
            <span class="far fa-pencil"></span>
            Editar
          </a>
          @endcan

        </div>
    </header>

      <div class="s-sb-grid s-sb-grid-cols-1 md:s-sb-grid-cols-2 s-sb-gap-8">
        <div>

          @if($sheet->dates->isNotEmpty())
            <h5 class="title title--sm s-sb-mb-2">Datas</h5>
          <div class="prose">
            <ul>
              @foreach($sheet->dates as $date)
                <li>{{ $date->isoFormat('LLL') }}</li>
              @endforeach
            </ul>
          </div>

          @endif

          @if($sheet->grupo)
              @if($sheet->grupo->logo)
                <img src="{{ $sheet->grupo->logo }}" class="s-sb-w-16 s-sb-float-right" style="width: 4rem;">
              @endif
                <h5 class="title title--sm s-sb-mb-2">Grupo</h5>
                {{ $sheet->grupo->nome }}
          @endif




        </div>
        <div>

          <h5 class="title title--sm s-sb-mb-2">Conteúdo</h5>

          @if($content['header']->isNotEmpty())
            <h6 class="title title--xs s-sb-mb-1">Cabeçalho</h6>
            <div class="sautor-list s-sb-mb-3">
              @foreach($content['header'] as $item)
                @include('songbook::sheets.item')
              @endforeach
            </div>
          @endif

          @if($content['main']->isNotEmpty())
            <h6 class="title title--xs s-sb-mb-1">Conteúdo</h6>
            <div class="sautor-list s-sb-mb-3">
              @foreach($content['main'] as $item)
                @include('songbook::sheets.item')
              @endforeach
            </div>
          @endif

          @if($content['footer']->isNotEmpty())
            <h6 class="title title--xs s-sb-mb-1">Rodapé</h6>
            <div class="sautor-list s-sb-mb-3">
              @foreach($content['footer'] as $item)
                @include('songbook::sheets.item')
              @endforeach
            </div>
          @endif

        </div>
      </div>

  </div>
@endsection

resources/views/songs/create.blade.php
@extends('songbook::layouts.main')

@section('sb.content')
  <div class="sautor-addon__full-container">
    <header class="sautor-addon__header">
      <h1 class="sautor-addon__header__title">
        Criar cântico
      </h1>
    </header>

      @php($scope = 'new-song')
      <form action="{{ route('songbook.canticos.store') }}" method="POST" data-vv-scope="{{ $scope }}">
        @csrf

        @include('songbook::songs.form')

        <div class="sautor-addon__actions">
          <button type="submit" class="button button--primary">Criar</button>
        </div>

      </form>
    </div>
@endsection

resources/views/songs/edit.blade.php
@extends('songbook::layouts.main')

@section('sb.content')
    <div class="sautor-addon__full-container">
        <header class="sautor-addon__header">
            <h1 class="sautor-addon__header__title">
                Editar cântico
            </h1>
        </header>

        @php($scope = 'edit-song')
        <form action="{{ route('songbook.canticos.update', $song) }}" method="POST" data-vv-scope="{{ $scope }}">
            @method('PUT')
            @csrf

            @include('songbook::songs.form')

            <div class="sautor-addon__actions">
                <button type="submit" class="button button--primary">Editar</button>
                @can('delete', $song)
                    <button type="button" class="button button--danger-light" @click.prevent="openModal('deleteModal')">
                        <span class="far fa-trash mr-2"></span>
                        Eliminar
                    </button>
                @endcan
            </div>

        </form>

    </div>

    @can('delete', $song)
        <modal id="deleteModal">
            <div class="modal__body modal__confirmation">
                <div class="modal__confirmation__icon">
                    <span class="fas fa-exclamation"></span>
                </div>
                <div class="modal__confirmation__content">
                    <h3 class="modal__confirmation__title">Eliminar cântico</h3>
                    <p class="modal__confirmation__text">
                        Tem a certeza que quer eliminar o cântico <strong>{{ $song->title }}</strong>?
                    </p>
                </div>
            </div>
            <form class="modal__footer" method="POST" action="{{ route('songbook.canticos.destroy', $song) }}">
                @csrf
                @method('DELETE')
                <button type="submit" class="button button--danger">Eliminar</button>
                <button type="button" class="button" @click.prevent="closeModal('deleteModal')">Cancelar</button>
            </form>
        </modal>
    @endcan
@endsection

resources/views/songs/grid-component.blade.php
@unless($songs->isEmpty())
    <div class="s-sb-columns-3xs -s-sb-m-2">
        @foreach($songs as $song)
            <a @can('view', $song) href="{{ route('songbook.canticos.show', $song) }}" @endcan class="block s-sb-p-4 s-sb-break-inside-avoid hover:s-sb-bg-gray-200">
                <p class="s-sb-font-bold">
                    <span class=" s-sb-underline s-sb-decoration-2 s-sb-decoration-primary-100 @unless(empty($song->chords)) s-sb-pr-5 @endunless ">{{ $song->title }}</span>

                    @unless(empty($song->chords))
                        <span class="fas fa-guitar s-sb-text-primary-300 -s-sb-ml-4"></span>
                    @endunless
                </p>
                <p class="s-sb-font-accent s-sb-text-xs s-sb-text-gray-600">
                    @if($song->by)
                        {{ $song->by }}
                        @if($song->grupo)
                            &middot;
                    @endif
                    @endif
                    @if($song->grupo)
                        {{ $song->grupo->nome_curto }}
                    @endif
                </p>
                @unless($song->tags->isEmpty())
                    <p class="s-sb-text-xs s-sb-text-gray-500 s-sb-mt-2">
                        <span class="fas fa-tag s-sb-text-gray-400"></span>
                        {{ $song->tags->pluck('name')->join(', ') }}
                    </p>
                @endunless
            </a>
        @endforeach
    </div>
@else
    <section class="sautor-list--empty songs-list--empty">
        {{ empty($empty_message) ? 'Não existem cânticos.' : $empty_message }}
    </section>
@endunless

resources/views/songs/index.blade.php
@extends('songbook::layouts.main')

@section('sb.content')
    <div class="sautor-addon__full-container">

        <header class="sautor-addon__header">
            <h1 class="sautor-addon__header__title">
                Cânticos
                <small>{{ $songs->count() }}</small>
            </h1>
            @can('create', \Sautor\Songbook\Models\Song::class)
                <div class="sautor-addon__header__actions">
                    <a href="{{ route('songbook.canticos.create') }}" class="button button--responsive">
                        <span class="far fa-plus"></span>
                        Criar
                    </a>
                </div>
            @endcan
        </header>

        <form method="GET">
            <div class="control s-sb-mb-4">

                <div class="control__addon control__addon--before">
                    <span class="control__addon__text"><span class="far fa-search"></span></span>
                </div>

                <input class="input" placeholder="Procurar..." name="search" id="search" type="search"
                       value="{{ request()->search }}"
                />

            </div>

        </form>

        @if($isSearch)
            <div class="s-sb-grid s-sb-grid-cols-1 md:s-sb-grid-cols-[auto_minmax(0,_1fr)] s-sb-gap-12 s-sb-mt-12">
                <div>
                    <p class="s-sb-font-headline s-sb-text-xl s-sb-text-gray-700">
                        Procura por
                        <strong class="s-sb-block s-sb-text-3xl s-sb-text-primary-700">{{ request()->search }}</strong>
                    </p>
                </div>
                @include('songbook::songs.grid-component')
            </div>
        @else
            <div class="s-sb-grid s-sb-grid-cols-[auto_minmax(0,_1fr)] s-sb-gap-x-8 s-sb-gap-y-24 s-sb-mt-12">
                @foreach($grouped_songs as $letter => $group_songs)
                    <div>
                        <div class="s-sb-font-headline s-sb-text-6xl s-sb-text-primary-700 text-center s-sb-sticky s-sb-top-4">{{ $letter }}</div>

                    </div>
                    @include('songbook::songs.grid-component', ['songs' => $group_songs])
                @endforeach
            </div>
        @endif

    </div>
@endsection

resources/views/songs/list-component.blade.php
@unless($songs->isEmpty())
  <section class="sautor-list sautor-list--full songs-list">
    @foreach($songs as $song)
      <div class="sautor-list__item">
        <div class="sautor-list__item__logo">
          <span class="sautor-list__item__logo__icon">
              <span class="fas fa-music-alt"></span>
          </span>
        </div>
        <a @can('view', $song) href="{{ route('songbook.canticos.show', $song) }}" @endcan class="sautor-list__item__data">
          <p class="sautor-list__item__name">
            {{ $song->title }}
            @foreach($song->tags as $tag)
              @include('songbook::tags.single-component')
            @endforeach
          </p>
          <p class="sautor-list__item__meta">
            @unless(empty($song->chords))
              <span class="far fa-guitar"></span>
              @if($song->by or $song->grupo)
                &middot;
              @endif
            @endunless
            @if($song->by)
              {{ $song->by }}
              @if($song->grupo)
                &middot;
              @endif
            @endif
            @if($song->grupo)
              {{ $song->grupo->nome_curto }}
            @endif
          </p>
        </a>

        @unless((empty($actions) or empty($a = $actions($song))) and (Auth::guest() or !Auth::user()->can('view', $song)))
          <div class="sautor-list__item__actions">
            @unless(empty($actions) or empty($a))
              @foreach($a as $action)
                <a title="{{ $action['label'] }}"
                   @if(!empty($action['link']))
                   href="{{ $action['link'] }}"
                   @elseif(!empty($action['modal']))
                   href="#" data-toggle="modal" data-target="#{{ $action['modal'] }}"
                    @endif
                >
                  <span class="{{ $action['icon'] }}"></span>
                </a>
              @endforeach
            @endunless
            @can('view', $song)
              <a title="Ver" href="{{ route('songbook.canticos.show', $song) }}">
                <span class="far fa-angle-right"></span>
              </a>
            @endcan
          </div>
        @endunless
      </div>
    @endforeach
  </section>
@else
  <section class="sautor-list--empty songs-list--empty">
    {{ empty($empty_message) ? 'Não existem cânticos.' : $empty_message }}
  </section>
@endunless

resources/views/songs/show.blade.php
@extends('songbook::layouts.main')

@section('sb.content')

    <div class="{{ empty($song->chords) ? 'sautor-addon__container' : 'sautor-addon__full-container' }}">


      <header class="sautor-addon__header">
        <div class="s-sb-flex-1">
          <h1 class="sautor-addon__header__title">
            {{ $song->title }}
            @if($song->by)
              <small>{{ $song->by }}</small>
            @endif
          </h1>
          @unless($song->tags->isEmpty() and !$song->grupo)
            <p class="s-sb-text-sm s-sb-text-gray-500 s-sb-mt-3 s-sb-ml-1">
              @if($song->grupo)
                <span class="fas fa-users s-sb-text-gray-400 s-sb-mr-1 s-sb-text-xs"></span>
                <span class="s-sb-mr-3">{{ $song->grupo->nome }}</span>
              @endif
              @unless($song->tags->isEmpty())
                <span class="fas fa-tag s-sb-text-gray-400 s-sb-mr-1 s-sb-text-xs"></span>
                <span class="s-sb-mr-3">{{ $song->tags->pluck('name')->join(', ') }}</span>
              @endunless
            </p>
          @endunless
        </div>

        @can('update', \Sautor\Songbook\Models\Song::class)
          <div class="sautor-addon__header__actions">
            <a href="{{ route('songbook.canticos.edit', $song) }}" class="button button--responsive">
              <span class="fas fa-pencil"></span>
              Editar
            </a>
          </div>
        @endcan
      </header>


      <div class="s-sb-grid s-sb-grid-cols-1 @unless(empty($song->chords)) md:s-sb-grid-cols-2 @endunless s-sb-gap-8">
        <div>
          <h3 class="title title--sm s-sb-mb-3">Letra</h3>
            <div class="s-sb-bg-white s-sb-px-6 s-sb-py-4 s-sb-rounded s-sb-shadow song-content">
              {!! $song->lyrics !!}
            </div>
        </div>
        @unless(empty($song->chords))
        <div>
          <h3 class="title title--sm s-sb-mb-3">Acordes</h3>
            <div class="s-sb-bg-white s-sb-px-6 s-sb-py-4 s-sb-rounded s-sb-shadow song-content song-content--chords">
              {!! $song->chords !!}
            </div>
        </div>
        @endunless
      </div>

    </div>
@endsection

resources/views/tags/create.blade.php
@extends('songbook::layouts.main')

@section('sb.content')
  <div class="sautor-addon__container">
    <header class="sautor-addon__header">
      <h1 class="sautor-addon__header__title">
        Criar etiqueta
      </h1>
    </header>

      @php($scope = 'new-tag')
      <form action="{{ route('songbook.etiquetas.store') }}" method="POST" data-vv-scope="{{ $scope }}">
        @csrf

        @include('songbook::tags.form')

        <div class="sautor-addon__actions">
          <button type="submit" class="button button--primary">Criar</button>
        </div>
      </form>
  </div>
@endsection

resources/views/tags/edit.blade.php
@extends('songbook::layouts.main')

@section('sb.content')
  <div class="sautor-addon__container">
    <header class="sautor-addon__header">
      <h1 class="sautor-addon__header__title">
        Editar etiqueta
      </h1>
    </header>

      @php($scope = 'edit-song')
      <form action="{{ route('songbook.etiquetas.update', $tag) }}" method="POST" data-vv-scope="{{ $scope }}">
        @method('PUT')
        @csrf

        @include('songbook::tags.form')

        <div class="sautor-addon__actions">
          <button type="submit" class="button button--primary">Editar</button>
          @can('delete', $tag)
            <button type="button" class="button button--danger-light" @click.prevent="openModal('deleteModal')">
              <span class="far fa-trash mr-2"></span>
              Eliminar
            </button>
          @endcan
        </div>

      </form>

  </div>

  @can('delete', $tag)
    <modal id="deleteModal">
      <div class="modal__body modal__confirmation">
        <div class="modal__confirmation__icon">
          <span class="fas fa-exclamation"></span>
        </div>
        <div class="modal__confirmation__content">
          <h3 class="modal__confirmation__title">Eliminar etiqueta</h3>
          <p class="modal__confirmation__text">
            Tem a certeza que quer eliminar a etiqueta <strong>{{ $tag->name }}</strong>?
          </p>
        </div>
      </div>
      <form class="modal__footer" method="POST" action="{{ route('songbook.etiquetas.destroy', $tag) }}">
        @csrf
        @method('DELETE')
        <button type="submit" class="button button--danger">Eliminar</button>
        <button type="button" class="button" @click.prevent="closeModal('deleteModal')">Cancelar</button>
      </form>
    </modal>
  @endcan
@endsection

resources/views/tags/index.blade.php
@extends('songbook::layouts.main')

@section('sb.content')
    <div class="sautor-addon__container">

        <header class="sautor-addon__header">
            <h1 class="sautor-addon__header__title">
                Etiquetas
            </h1>
            @can('create', \Sautor\Songbook\Models\Tag::class)
                <div class="sautor-addon__header__actions">
                    <a href="{{ route('songbook.etiquetas.create') }}" class="button button--responsive">
                        <span class="far fa-plus"></span>
                        Criar
                    </a>
                </div>
            @endcan
        </header>

        @include('songbook::tags.list-component')

    </div>
@endsection

resources/views/tags/single-component.blade.php
<span class="badge badge-secondary" @if($tag->grupo and $tag->grupo->cor) style="background-color: {{ $tag->grupo->cor }}; color: white;" @endif>{{ $tag->name }}</span>